const loginUsers = [
  {
    userId: "U2023001",
    password: "pass123",
    name: "Aarav Sharma",
    semester: 2,
    yearOfJoining: 2023,
    isAdmin: false,
  },
  {
    userId: "U2023002",
    password: "password456",
    name: "Diya Mehra",
    semester: 4,
    yearOfJoining: 2022,
    isAdmin: false,
  },
  {
    userId: "U2023003",
    password: "mypassword",
    name: "Vivaan Gupta",
    semester: 1,
    yearOfJoining: 2024,
    isAdmin: false,
  },
  {
    userId: "U2023004",
    password: "qwerty789",
    name: "Anaya Singh",
    semester: 3,
    yearOfJoining: 2023,
    isAdmin: false,
  },
  {
    userId: "UADMIN01",
    password: "adminpass",
    name: "Prof. Neha Verma",
    isAdmin: true,
  },
  {
    userId: "UADMIN02",
    password: "secureadmin",
    name: "Dr. Karan Patel",
    isAdmin: true,
  },
  {
    userId: "U2023005",
    password: "letmein",
    name: "Kabir Desai",
    semester: 5,
    yearOfJoining: 2021,
    isAdmin: false,
  },
  {
    userId: "U2023006",
    password: "12345678",
    name: "Meera Joshi",
    semester: 6,
    yearOfJoining: 2020,
    isAdmin: false,
  },
  {
    userId: "U2023007",
    password: "studentpwd",
    name: "Arjun Nair",
    semester: 2,
    yearOfJoining: 2023,
    isAdmin: false,
  },
  {
    userId: "UADMIN03",
    password: "admin321",
    name: "Admin Anjali Rao",
    isAdmin: true,
  },
];

const dummyData = [
  {
    id: "UNI2025001",
    name: "Aarav Sharma",
    semester: 1,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025002",
    name: "Ishita Patel",
    semester: 2,
    feeStatus: "Unpaid",
    remainingFeesAmount: 15000,
  },
  {
    id: "UNI2025003",
    name: "Rohan Das",
    semester: 3,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025004",
    name: "Priya Singh",
    semester: 4,
    feeStatus: "Unpaid",
    remainingFeesAmount: 20000,
  },
  {
    id: "UNI2025005",
    name: "Kunal Verma",
    semester: 5,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025006",
    name: "Ananya Rao",
    semester: 6,
    feeStatus: "Unpaid",
    remainingFeesAmount: 18000,
  },
  {
    id: "UNI2025007",
    name: "Vikram Joshi",
    semester: 7,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025008",
    name: "Neha Gupta",
    semester: 8,
    feeStatus: "Unpaid",
    remainingFeesAmount: 22000,
  },
  {
    id: "UNI2025009",
    name: "Manav Mehta",
    semester: 1,
    feeStatus: "Unpaid",
    remainingFeesAmount: 12000,
  },
  {
    id: "UNI2025010",
    name: "Simran Kaur",
    semester: 2,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025011",
    name: "Rahul Nair",
    semester: 3,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025012",
    name: "Sanya Jain",
    semester: 4,
    feeStatus: "Unpaid",
    remainingFeesAmount: 17000,
  },
  {
    id: "UNI2025013",
    name: "Dev Patel",
    semester: 5,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025014",
    name: "Mehak Bansal",
    semester: 6,
    feeStatus: "Unpaid",
    remainingFeesAmount: 13500,
  },
  {
    id: "UNI2025015",
    name: "Kabir Malhotra",
    semester: 7,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025016",
    name: "Aditi Chauhan",
    semester: 8,
    feeStatus: "Unpaid",
    remainingFeesAmount: 20000,
  },
  {
    id: "UNI2025017",
    name: "Yash Thakur",
    semester: 1,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025018",
    name: "Sneha Reddy",
    semester: 2,
    feeStatus: "Unpaid",
    remainingFeesAmount: 14500,
  },
  {
    id: "UNI2025019",
    name: "Tanishq Roy",
    semester: 3,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025020",
    name: "Divya Kapoor",
    semester: 4,
    feeStatus: "Unpaid",
    remainingFeesAmount: 19000,
  },
  {
    id: "UNI2025021",
    name: "Arjun Sinha",
    semester: 5,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025022",
    name: "Kiara Desai",
    semester: 6,
    feeStatus: "Unpaid",
    remainingFeesAmount: 15500,
  },
  {
    id: "UNI2025023",
    name: "Nikhil Yadav",
    semester: 7,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025024",
    name: "Riya Ghosh",
    semester: 8,
    feeStatus: "Unpaid",
    remainingFeesAmount: 17500,
  },
  {
    id: "UNI2025025",
    name: "Aditya Khanna",
    semester: 1,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025026",
    name: "Sakshi Mehra",
    semester: 2,
    feeStatus: "Unpaid",
    remainingFeesAmount: 16000,
  },
  {
    id: "UNI2025027",
    name: "Aman Dubey",
    semester: 3,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025028",
    name: "Tanya Bhatt",
    semester: 4,
    feeStatus: "Unpaid",
    remainingFeesAmount: 18000,
  },
  {
    id: "UNI2025029",
    name: "Rudra Jaiswal",
    semester: 5,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025030",
    name: "Avni Seth",
    semester: 6,
    feeStatus: "Unpaid",
    remainingFeesAmount: 19500,
  },
  {
    id: "UNI2025031",
    name: "Harsh Mittal",
    semester: 7,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025032",
    name: "Ira Shah",
    semester: 8,
    feeStatus: "Unpaid",
    remainingFeesAmount: 21000,
  },
  {
    id: "UNI2025033",
    name: "Parth Agrawal",
    semester: 1,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025034",
    name: "Mitali Rawat",
    semester: 2,
    feeStatus: "Unpaid",
    remainingFeesAmount: 14000,
  },
  {
    id: "UNI2025035",
    name: "Siddharth Rao",
    semester: 3,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025036",
    name: "Ishaan Kapoor",
    semester: 4,
    feeStatus: "Unpaid",
    remainingFeesAmount: 18500,
  },
  {
    id: "UNI2025037",
    name: "Zoya Khan",
    semester: 5,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025038",
    name: "Jay Joshi",
    semester: 6,
    feeStatus: "Unpaid",
    remainingFeesAmount: 15000,
  },
  {
    id: "UNI2025039",
    name: "Pooja Rathi",
    semester: 7,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025040",
    name: "Veer Mahajan",
    semester: 8,
    feeStatus: "Unpaid",
    remainingFeesAmount: 20500,
  },
  {
    id: "UNI2025041",
    name: "Anika Suri",
    semester: 1,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025042",
    name: "Laksh Chaudhary",
    semester: 2,
    feeStatus: "Unpaid",
    remainingFeesAmount: 16000,
  },
  {
    id: "UNI2025043",
    name: "Kritika Basu",
    semester: 3,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025044",
    name: "Yuvraj Sharma",
    semester: 4,
    feeStatus: "Unpaid",
    remainingFeesAmount: 17500,
  },
  {
    id: "UNI2025045",
    name: "Meera Nambiar",
    semester: 5,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025046",
    name: "Dhruv Saxena",
    semester: 6,
    feeStatus: "Unpaid",
    remainingFeesAmount: 18500,
  },
  {
    id: "UNI2025047",
    name: "Trisha Dey",
    semester: 7,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025048",
    name: "Arnav Kulkarni",
    semester: 8,
    feeStatus: "Unpaid",
    remainingFeesAmount: 19500,
  },
  {
    id: "UNI2025049",
    name: "Saanvi Pillai",
    semester: 1,
    feeStatus: "Paid",
    remainingFeesAmount: 0,
  },
  {
    id: "UNI2025050",
    name: "Devika Rane",
    semester: 2,
    feeStatus: "Unpaid",
    remainingFeesAmount: 15000,
  },
];

export { dummyData, loginUsers };
